import Head from 'next/head';
import Form from '../components/Form';
import Basic from '../components/NewForm';

const isModal = true;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* isModal && (
      <div className="fixed top-0 left-0 z-[1000] h-screen w-screen bg-slate-900/90 flex items-center justify-center">
        <div className="h-40 w-40 bg-white flex items-center justify-center">MODAL</div>
      </div>
      ) */}
      <main>
        <h1 className="text-3xl font-bold underline mb-7">
          Form
        </h1>
        <Form />
        {/*<Basic />*/}
      </main>
    </>
  )
}
